# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/helper-string-parser-7.27.1" = {
      name = "_at_babel_slash_helper-string-parser";
      packageName = "@babel/helper-string-parser";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-string-parser/-/helper-string-parser-7.27.1.tgz";
        sha512 = "qMlSxKbpRlAridDExk92nSobyDdpPijUq2DW6oDnUqd0iOGxmQjyqhMIihI9+zv4LPyZdRje2cavWPbCbWm3eA==";
      };
    };
    "@babel/helper-validator-identifier-7.28.5" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.28.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.28.5.tgz";
        sha512 = "qSs4ifwzKJSV39ucNjsvc6WVHs6b7S03sOh2OcHF9UHfVPqWWALUsNUVzhSBiItjRZoLHx7nIarVjqKVusUZ1Q==";
      };
    };
    "@babel/parser-7.29.0" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.29.0.tgz";
        sha512 = "IyDgFV5GeDUVX4YdF/3CPULtVGSXXMLh1xVIgdCgxApktqnQV0r7/8Nqthg+8YLGaAtdyIlo2qIdZrbCv4+7ww==";
      };
    };
    "@babel/types-7.29.0" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.29.0.tgz";
        sha512 = "LwdZHpScM4Qz8Xw2iKSzS+cfglZzJGvofQICy7W7v4caru4EaAmyUuO6BGrbyQ2mYV11W0U8j5mBhd14dd3B0A==";
      };
    };
    "@prisma/config-6.19.0-dev.10" = {
      name = "_at_prisma_slash_config";
      packageName = "@prisma/config";
      version = "6.19.0-dev.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prisma/config/-/config-6.19.0-dev.10.tgz";
        sha512 = "y3jJxFpPw8shOW+h1bpKIbEMrVOLOupcgzAxI+ixMOLzHH7041BYrotftRvAz/edQhEAeG2nAVDOyKS45o+H8A==";
      };
    };
    "@prisma/config-7.3.0" = {
      name = "_at_prisma_slash_config";
      packageName = "@prisma/config";
      version = "7.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prisma/config/-/config-7.3.0.tgz";
        sha512 = "QyMV67+eXF7uMtKxTEeQqNu/Be7iH+3iDZOQZW5ttfbSwBamCSdwPszA0dum+Wx27I7anYTPLmRmMORKViSW1A==";
      };
    };
    "@prisma/config-7.4.0-dev.17" = {
      name = "_at_prisma_slash_config";
      packageName = "@prisma/config";
      version = "7.4.0-dev.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prisma/config/-/config-7.4.0-dev.17.tgz";
        sha512 = "zXtrQUSCmLKOKU+gDmwntKLbu4KJlioUdXjLK0hqyZErQH9RcVIfpdvKJ8XUaEInPwB6DOax1pGZxbOx4NXvHw==";
      };
    };
    "@prisma/prisma-schema-wasm-6.19.0-26.2ba551f319ab1df4bc874a89965d8b3641056773" = {
      name = "_at_prisma_slash_prisma-schema-wasm";
      packageName = "@prisma/prisma-schema-wasm";
      version = "6.19.0-26.2ba551f319ab1df4bc874a89965d8b3641056773";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prisma/prisma-schema-wasm/-/prisma-schema-wasm-6.19.0-26.2ba551f319ab1df4bc874a89965d8b3641056773.tgz";
        sha512 = "5au1UH9+jky4TtIdgxDUA9Mk+40R2hDwZnhjjzR1io7WFtIKP6e5DI7yQ5QVysY8Ves8KWDsvwzDOn6gYNY4iA==";
      };
    };
    "@prisma/prisma-schema-wasm-7.3.0-16.9d6ad21cbbceab97458517b147a6a09ff43aa735" = {
      name = "_at_prisma_slash_prisma-schema-wasm";
      packageName = "@prisma/prisma-schema-wasm";
      version = "7.3.0-16.9d6ad21cbbceab97458517b147a6a09ff43aa735";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prisma/prisma-schema-wasm/-/prisma-schema-wasm-7.3.0-16.9d6ad21cbbceab97458517b147a6a09ff43aa735.tgz";
        sha512 = "pL9W918JLoK9fdAccH07ryjN9D4TZU1H3zBrLtYZbd+YhsAYQVvyM8hhyxzv8UrXVDKwsiYWoMdTb2PC+cjy3A==";
      };
    };
    "@prisma/prisma-schema-wasm-7.4.0-15.6129681d45ea4510d3372dd5b28f6b89275848a5" = {
      name = "_at_prisma_slash_prisma-schema-wasm";
      packageName = "@prisma/prisma-schema-wasm";
      version = "7.4.0-15.6129681d45ea4510d3372dd5b28f6b89275848a5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prisma/prisma-schema-wasm/-/prisma-schema-wasm-7.4.0-15.6129681d45ea4510d3372dd5b28f6b89275848a5.tgz";
        sha512 = "zUB/hGs/MmVLLtIYIHQuukZ26oZbF+MhZrfsfXhithCyZlLkiTa6MYof6ju9Uq1XAx38adT1OYzR7l0O0LykTg==";
      };
    };
    "@prisma/schema-files-loader-6.19.0-dev.10" = {
      name = "_at_prisma_slash_schema-files-loader";
      packageName = "@prisma/schema-files-loader";
      version = "6.19.0-dev.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prisma/schema-files-loader/-/schema-files-loader-6.19.0-dev.10.tgz";
        sha512 = "FpjL53iN1ApEUyNbbaBJ2Yn575SMYiwplEeMpeSS4249DSf4O9B1l+RB6wLnXQ6Gk415GX4Y6+MWS3DAZfw4Ow==";
      };
    };
    "@prisma/schema-files-loader-7.3.0" = {
      name = "_at_prisma_slash_schema-files-loader";
      packageName = "@prisma/schema-files-loader";
      version = "7.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prisma/schema-files-loader/-/schema-files-loader-7.3.0.tgz";
        sha512 = "NDGctetgHLXRQodiiFIm0QPxq1ZJMo1+d66K3oOKKUKCLYOHnH2VemZbcwsf4oAXKlTRyLnxMR4Q2xiGTyNGRQ==";
      };
    };
    "@prisma/schema-files-loader-7.4.0-dev.17" = {
      name = "_at_prisma_slash_schema-files-loader";
      packageName = "@prisma/schema-files-loader";
      version = "7.4.0-dev.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prisma/schema-files-loader/-/schema-files-loader-7.4.0-dev.17.tgz";
        sha512 = "tTWuoDI5J2MYeYSnqRH7J0ujoAaYgtb4qhBzwxdnG3zmFAvmv7QR2whg5112WSSSC6nbJsmV52b5BI1bGzm8pw==";
      };
    };
    "@standard-schema/spec-1.1.0" = {
      name = "_at_standard-schema_slash_spec";
      packageName = "@standard-schema/spec";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@standard-schema/spec/-/spec-1.1.0.tgz";
        sha512 = "l2aFy5jALhniG5HgqrD6jXLi/rUWrKvqN/qJx6yoJsgKhblVd+iqqU4RCXavm/jPityDo5TCvKMnpjKnOriy0w==";
      };
    };
    "@types/js-levenshtein-1.1.3" = {
      name = "_at_types_slash_js-levenshtein";
      packageName = "@types/js-levenshtein";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/js-levenshtein/-/js-levenshtein-1.1.3.tgz";
        sha512 = "jd+Q+sD20Qfu9e2aEXogiO3vpOC1PYJOUdyN9gvs4Qrvkg4wF43L5OhqrPeokdv8TL0/mXoYfpkcoGZMNN2pkQ==";
      };
    };
    "c12-3.1.0" = {
      name = "c12";
      packageName = "c12";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/c12/-/c12-3.1.0.tgz";
        sha512 = "uWoS8OU1MEIsOv8p/5a82c3H31LsWVR5qiyXVfBNOzfffjUWtPnhAb4BYI2uG2HfGmZmFjCtui5XNWaps+iFuw==";
      };
    };
    "chokidar-4.0.3" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-4.0.3.tgz";
        sha512 = "Qgzu8kfBvo+cA4962jnP1KkS6Dop5NS6g7R5LFYJr4b8Ub94PPQXUksCw9PvXoeXPRRddRNC5C1JQUR2SMGtnA==";
      };
    };
    "citty-0.1.6" = {
      name = "citty";
      packageName = "citty";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/citty/-/citty-0.1.6.tgz";
        sha512 = "tskPPKEs8D2KPafUypv2gxwJP8h/OaJmC82QQGGDQcHvXX43xF2VDACcJVmZ0EuSxkpO9Kc4MlrA3q0+FG58AQ==";
      };
    };
    "citty-0.2.0" = {
      name = "citty";
      packageName = "citty";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/citty/-/citty-0.2.0.tgz";
        sha512 = "8csy5IBFI2ex2hTVpaHN2j+LNE199AgiI7y4dMintrr8i0lQiFn+0AWMZrWdHKIgMOer65f8IThysYhoReqjWA==";
      };
    };
    "confbox-0.2.4" = {
      name = "confbox";
      packageName = "confbox";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/confbox/-/confbox-0.2.4.tgz";
        sha512 = "ysOGlgTFbN2/Y6Cg3Iye8YKulHw+R2fNXHrgSmXISQdMnomY6eNDprVdW9R5xBguEqI954+S6709UyiO7B+6OQ==";
      };
    };
    "consola-3.4.2" = {
      name = "consola";
      packageName = "consola";
      version = "3.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/consola/-/consola-3.4.2.tgz";
        sha512 = "5IKcdX0nnYavi6G7TtOhwkYzyjfJlatbjMjuLSfE2kYT5pMDOilZ4OvMhi637CcDICTmz3wARPoyhqyX1Y+XvA==";
      };
    };
    "deepmerge-ts-7.1.5" = {
      name = "deepmerge-ts";
      packageName = "deepmerge-ts";
      version = "7.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/deepmerge-ts/-/deepmerge-ts-7.1.5.tgz";
        sha512 = "HOJkrhaYsweh+W+e74Yn7YStZOilkoPb6fycpwNLKzSPtruFs48nYis0zy5yJz1+ktUhHxoRDJ27RQAWLIJVJw==";
      };
    };
    "defu-6.1.4" = {
      name = "defu";
      packageName = "defu";
      version = "6.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/defu/-/defu-6.1.4.tgz";
        sha512 = "mEQCMmwJu317oSz8CwdIOdwf3xMif1ttiM8LTufzc3g6kR+9Pe236twL8j3IYT1F7GfRgGcW6MWxzZjLIkuHIg==";
      };
    };
    "destr-2.0.5" = {
      name = "destr";
      packageName = "destr";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/destr/-/destr-2.0.5.tgz";
        sha512 = "ugFTXCtDZunbzasqBxrK93Ik/DRYsO6S/fedkWEMKqt04xZ4csmnmwGDBAb07QWNaGMAmnTIemsYZCksjATwsA==";
      };
    };
    "dotenv-16.6.1" = {
      name = "dotenv";
      packageName = "dotenv";
      version = "16.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dotenv/-/dotenv-16.6.1.tgz";
        sha512 = "uBq4egWHTcTt33a72vpSG0z3HnPuIl6NqYcTrKEg2azoEyl2hpW0zqlxysq2pK9HlDIHyHyakeYaYnSAwd8bow==";
      };
    };
    "effect-3.18.4" = {
      name = "effect";
      packageName = "effect";
      version = "3.18.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/effect/-/effect-3.18.4.tgz";
        sha512 = "b1LXQJLe9D11wfnOKAk3PKxuqYshQ0Heez+y5pnkd3jLj1yx9QhM72zZ9uUrOQyNvrs2GZZd/3maL0ZV18YuDA==";
      };
    };
    "empathic-2.0.0" = {
      name = "empathic";
      packageName = "empathic";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/empathic/-/empathic-2.0.0.tgz";
        sha512 = "i6UzDscO/XfAcNYD75CfICkmfLedpyPDdozrLMmQc5ORaQcdMoc21OnlEylMIqI7U8eniKrPMxxtj8k0vhmJhA==";
      };
    };
    "exsolve-1.0.8" = {
      name = "exsolve";
      packageName = "exsolve";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/exsolve/-/exsolve-1.0.8.tgz";
        sha512 = "LmDxfWXwcTArk8fUEnOfSZpHOJ6zOMUJKOtFLFqJLoKJetuQG874Uc7/Kki7zFLzYybmZhp1M7+98pfMqeX8yA==";
      };
    };
    "fast-check-3.23.2" = {
      name = "fast-check";
      packageName = "fast-check";
      version = "3.23.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-check/-/fast-check-3.23.2.tgz";
        sha512 = "h5+1OzzfCC3Ef7VbtKdcv7zsstUQwUDlYpUTvjeUsJAssPgLn7QzbboPtL5ro04Mq0rPOsMzl7q5hIbRs2wD1A==";
      };
    };
    "fs-extra-11.3.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "11.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-11.3.0.tgz";
        sha512 = "Z4XaCL6dUDHfP/jT25jJKMmtxvuwbkrD1vNSMFlo9lNLY2c5FHYSQgHPRZUjAB26TpDEoW9HCOgplrdbaPV/ew==";
      };
    };
    "giget-2.0.0" = {
      name = "giget";
      packageName = "giget";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/giget/-/giget-2.0.0.tgz";
        sha512 = "L5bGsVkxJbJgdnwyuheIunkGatUF/zssUoxxjACCseZYAVbaqdh9Tsmmlkl8vYan09H7sbvKt4pS8GqKLBrEzA==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "jiti-2.6.1" = {
      name = "jiti";
      packageName = "jiti";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jiti/-/jiti-2.6.1.tgz";
        sha512 = "ekilCSN1jwRvIbgeg/57YFh8qQDNbwDb9xT/qu2DAHbFFZUicIl4ygVaAvzveMhMVr3LnpSKTNnwt8PoOfmKhQ==";
      };
    };
    "js-levenshtein-1.1.6" = {
      name = "js-levenshtein";
      packageName = "js-levenshtein";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-levenshtein/-/js-levenshtein-1.1.6.tgz";
        sha512 = "X2BB11YZtrRqY4EnQcLX5Rh373zbK4alC1FW7D7MBhL2gtcC17cTnr6DmfHZeS0s2rTHjUTMMHfG7gO8SSdw+g==";
      };
    };
    "jsonfile-6.2.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-6.2.0.tgz";
        sha512 = "FGuPw30AdOIUTRMC2OMRtQV+jkVj2cfPqSeWXv1NEAJ1qZ5zb1X6z1mFhbfOB/iy3ssJCD+3KuZ8r8C3uVFlAg==";
      };
    };
    "klona-2.0.6" = {
      name = "klona";
      packageName = "klona";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/klona/-/klona-2.0.6.tgz";
        sha512 = "dhG34DXATL5hSxJbIexCft8FChFXtmskoZYnoPWjXQuebWYCNkVeV3KkGegCK9CP1oswI/vQibS2GY7Em/sJJA==";
      };
    };
    "magicast-0.3.5" = {
      name = "magicast";
      packageName = "magicast";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/magicast/-/magicast-0.3.5.tgz";
        sha512 = "L0WhttDl+2BOsybvEOLK7fW3UA0OQ0IQ2d6Zl2x/a6vVRs3bAY0ECOSHHeL5jD+SbOpOCUEi0y1DgHEn9Qn1AQ==";
      };
    };
    "node-fetch-native-1.6.7" = {
      name = "node-fetch-native";
      packageName = "node-fetch-native";
      version = "1.6.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch-native/-/node-fetch-native-1.6.7.tgz";
        sha512 = "g9yhqoedzIUm0nTnTqAQvueMPVOuIY16bqgAJJC8XOOubYFNwz6IER9qs0Gq2Xd0+CecCKFjtdDTMA4u4xG06Q==";
      };
    };
    "nypm-0.6.5" = {
      name = "nypm";
      packageName = "nypm";
      version = "0.6.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/nypm/-/nypm-0.6.5.tgz";
        sha512 = "K6AJy1GMVyfyMXRVB88700BJqNUkByijGJM8kEHpLdcAt+vSQAVfkWWHYzuRXHSY6xA2sNc5RjTj0p9rE2izVQ==";
      };
    };
    "ohash-2.0.11" = {
      name = "ohash";
      packageName = "ohash";
      version = "2.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/ohash/-/ohash-2.0.11.tgz";
        sha512 = "RdR9FQrFwNBNXAr4GixM8YaRZRJ5PUWbKYbE5eOsrwAjJW0q2REGcf79oYPsLyskQCZG1PLN+S/K1V00joZAoQ==";
      };
    };
    "pathe-2.0.3" = {
      name = "pathe";
      packageName = "pathe";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pathe/-/pathe-2.0.3.tgz";
        sha512 = "WUjGcAqP1gQacoQe+OBJsFA7Ld4DyXuUIjZ5cc75cLHvJ7dtNsTugphxIADwspS+AraAUePCKrSVtPLFj/F88w==";
      };
    };
    "perfect-debounce-1.0.0" = {
      name = "perfect-debounce";
      packageName = "perfect-debounce";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/perfect-debounce/-/perfect-debounce-1.0.0.tgz";
        sha512 = "xCy9V055GLEqoFaHoC1SoLIaLmWctgCUaBaWxDZ7/Zx4CTyX7cJQLJOok/orfjZAh9kEYpjJa4d0KcJmCbctZA==";
      };
    };
    "pkg-types-2.3.0" = {
      name = "pkg-types";
      packageName = "pkg-types";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pkg-types/-/pkg-types-2.3.0.tgz";
        sha512 = "SIqCzDRg0s9npO5XQ3tNZioRY1uK06lA41ynBC1YmFTmnY6FjUjVt6s4LoADmwoig1qqD0oK8h1p/8mlMx8Oig==";
      };
    };
    "pure-rand-6.1.0" = {
      name = "pure-rand";
      packageName = "pure-rand";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pure-rand/-/pure-rand-6.1.0.tgz";
        sha512 = "bVWawvoZoBYpp6yIoQtQXHZjmz35RSVHnUOTefl8Vcjr8snTPY1wnpSPMWekcFwbxI6gtmT7rSYPFvz71ldiOA==";
      };
    };
    "rc9-2.1.2" = {
      name = "rc9";
      packageName = "rc9";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rc9/-/rc9-2.1.2.tgz";
        sha512 = "btXCnMmRIBINM2LDZoEmOogIZU7Qe7zn4BpomSKZ/ykbLObuBdvG+mFq11DL6fjH1DRwHhrlgtYWG96bJiC7Cg==";
      };
    };
    "readdirp-4.1.2" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-4.1.2.tgz";
        sha512 = "GDhwkLfywWL2s6vEjyhri+eXmfH6j1L7JE27WhqLeYzoh/A3DBaYGEj2H/HFZCn/kMfim73FXxEJTw06WtxQwg==";
      };
    };
    "source-map-js-1.2.1" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.1.tgz";
        sha512 = "UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
      };
    };
    "tinyexec-1.0.2" = {
      name = "tinyexec";
      packageName = "tinyexec";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tinyexec/-/tinyexec-1.0.2.tgz";
        sha512 = "W/KYk+NFhkmsYpuHq5JykngiOCnxeVL8v8dFnqxSD8qEEdRfXk1SDM6JzNqcERbcGYj9tMrDQBYV9cjgnunFIg==";
      };
    };
    "universalify-2.0.1" = {
      name = "universalify";
      packageName = "universalify";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-2.0.1.tgz";
        sha512 = "gptHNQghINnc/vTGIk0SOFGFNXw7JVrlRUtConJRlvaw6DuX0wO5Jeko9sWrMBhh+PsYAZ7oXAiOnf/UKogyiw==";
      };
    };
    "vscode-jsonrpc-8.1.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.1.0.tgz";
        sha512 = "6TDy/abTQk+zDGYazgbIPc+4JoXdwC8NHU9Pbn4UJP1fehUyZmM4RHp5IthX7A6L5KS30PRui+j+tbbMMMafdw==";
      };
    };
    "vscode-languageserver-8.1.0" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-8.1.0.tgz";
        sha512 = "eUt8f1z2N2IEUDBsKaNapkz7jl5QpskN2Y0G01T/ItMxBxw1fJwvtySGB9QMecatne8jFIWJGWI61dWjyTLQsw==";
      };
    };
    "vscode-languageserver-protocol-3.17.3" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.3.tgz";
        sha512 = "924/h0AqsMtA5yK22GgMtCYiMdCOtWTSGgUOkgEDX+wk2b0x4sAfLiO4NxBxqbiVtz7K7/1/RgVrVI0NClZwqA==";
      };
    };
    "vscode-languageserver-textdocument-1.0.11" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.11.tgz";
        sha512 = "X+8T3GoiwTVlJbicx/sIAF+yuJAqz8VvwJyoMVhwEMoEKE/fkDmrqUgDMyBECcM2A2frVZIUj5HI/ErRXCfOeA==";
      };
    };
    "vscode-languageserver-types-3.17.3" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.3.tgz";
        sha512 = "SYU4z1dL0PyIMd4Vj8YOqFvHu7Hz/enbWtpfnVbJHU4Nd1YNYx8u0ennumc6h48GQNeOLxmwySmnADouT/AuZA==";
      };
    };
    "vscode-uri-3.1.0" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.1.0.tgz";
        sha512 = "/BpdSx+yCQGnCvecbyXdxHDkuk55/G3xwnC0GqY4gmQ3j+A+g8kzzgB4Nk/SINjqn6+waqw3EgbVF2QKExkRxQ==";
      };
    };
  };
in
{
  "@prisma/language-server" = nodeEnv.buildNodePackage {
    name = "_at_prisma_slash_language-server";
    packageName = "@prisma/language-server";
    version = "31.4.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@prisma/language-server/-/language-server-31.4.0.tgz";
      sha512 = "AjhjQp5SHuFkNrCNvS/gAdujgNfd9NL4qLZuhGIL5dGoG5pPlr+dXzTBZtott+wyxF1xklkP+bQOZggOLGV5aQ==";
    };
    dependencies = [
      sources."@babel/helper-string-parser-7.27.1"
      sources."@babel/helper-validator-identifier-7.28.5"
      sources."@babel/parser-7.29.0"
      sources."@babel/types-7.29.0"
      sources."@prisma/config-7.3.0"
      sources."@prisma/prisma-schema-wasm-7.3.0-16.9d6ad21cbbceab97458517b147a6a09ff43aa735"
      sources."@prisma/schema-files-loader-7.3.0"
      sources."@standard-schema/spec-1.1.0"
      sources."@types/js-levenshtein-1.1.3"
      sources."c12-3.1.0"
      sources."chokidar-4.0.3"
      sources."citty-0.1.6"
      sources."confbox-0.2.4"
      sources."consola-3.4.2"
      sources."deepmerge-ts-7.1.5"
      sources."defu-6.1.4"
      sources."destr-2.0.5"
      sources."dotenv-16.6.1"
      sources."effect-3.18.4"
      sources."empathic-2.0.0"
      sources."exsolve-1.0.8"
      sources."fast-check-3.23.2"
      sources."fs-extra-11.3.0"
      sources."giget-2.0.0"
      sources."graceful-fs-4.2.11"
      sources."jiti-2.6.1"
      sources."js-levenshtein-1.1.6"
      sources."jsonfile-6.2.0"
      sources."klona-2.0.6"
      sources."magicast-0.3.5"
      sources."node-fetch-native-1.6.7"
      (sources."nypm-0.6.5" // {
        dependencies = [
          sources."citty-0.2.0"
        ];
      })
      sources."ohash-2.0.11"
      sources."pathe-2.0.3"
      sources."perfect-debounce-1.0.0"
      sources."pkg-types-2.3.0"
      sources."pure-rand-6.1.0"
      sources."rc9-2.1.2"
      sources."readdirp-4.1.2"
      sources."source-map-js-1.2.1"
      sources."tinyexec-1.0.2"
      sources."universalify-2.0.1"
      sources."vscode-jsonrpc-8.1.0"
      sources."vscode-languageserver-8.1.0"
      sources."vscode-languageserver-protocol-3.17.3"
      sources."vscode-languageserver-textdocument-1.0.11"
      sources."vscode-languageserver-types-3.17.3"
      sources."vscode-uri-3.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prisma Language Server";
      homepage = "https://github.com/prisma/language-tools#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@prisma/language-server-dev" = nodeEnv.buildNodePackage {
    name = "_at_prisma_slash_language-server";
    packageName = "@prisma/language-server";
    version = "31.4.17";
    src = fetchurl {
      url = "https://registry.npmjs.org/@prisma/language-server/-/language-server-31.4.17.tgz";
      sha512 = "ZxmiTLAAqWB1cE4vLwq+2YKUsZTxU+0M4pYx+TDoJMOBuulvBDfvhWKiCxrPaf+bWTu7MzTZTZUZLtRygXN6nQ==";
    };
    dependencies = [
      sources."@babel/helper-string-parser-7.27.1"
      sources."@babel/helper-validator-identifier-7.28.5"
      sources."@babel/parser-7.29.0"
      sources."@babel/types-7.29.0"
      sources."@prisma/config-7.4.0-dev.17"
      sources."@prisma/prisma-schema-wasm-7.4.0-15.6129681d45ea4510d3372dd5b28f6b89275848a5"
      sources."@prisma/schema-files-loader-7.4.0-dev.17"
      sources."@standard-schema/spec-1.1.0"
      sources."@types/js-levenshtein-1.1.3"
      sources."c12-3.1.0"
      sources."chokidar-4.0.3"
      sources."citty-0.1.6"
      sources."confbox-0.2.4"
      sources."consola-3.4.2"
      sources."deepmerge-ts-7.1.5"
      sources."defu-6.1.4"
      sources."destr-2.0.5"
      sources."dotenv-16.6.1"
      sources."effect-3.18.4"
      sources."empathic-2.0.0"
      sources."exsolve-1.0.8"
      sources."fast-check-3.23.2"
      sources."fs-extra-11.3.0"
      sources."giget-2.0.0"
      sources."graceful-fs-4.2.11"
      sources."jiti-2.6.1"
      sources."js-levenshtein-1.1.6"
      sources."jsonfile-6.2.0"
      sources."klona-2.0.6"
      sources."magicast-0.3.5"
      sources."node-fetch-native-1.6.7"
      (sources."nypm-0.6.5" // {
        dependencies = [
          sources."citty-0.2.0"
        ];
      })
      sources."ohash-2.0.11"
      sources."pathe-2.0.3"
      sources."perfect-debounce-1.0.0"
      sources."pkg-types-2.3.0"
      sources."pure-rand-6.1.0"
      sources."rc9-2.1.2"
      sources."readdirp-4.1.2"
      sources."source-map-js-1.2.1"
      sources."tinyexec-1.0.2"
      sources."universalify-2.0.1"
      sources."vscode-jsonrpc-8.1.0"
      sources."vscode-languageserver-8.1.0"
      sources."vscode-languageserver-protocol-3.17.3"
      sources."vscode-languageserver-textdocument-1.0.11"
      sources."vscode-languageserver-types-3.17.3"
      sources."vscode-uri-3.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prisma Language Server";
      homepage = "https://github.com/prisma/language-tools#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@prisma/language-server-integration" = nodeEnv.buildNodePackage {
    name = "_at_prisma_slash_language-server";
    packageName = "@prisma/language-server";
    version = "6.19.0-hotfix.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/@prisma/language-server/-/language-server-6.19.0-hotfix.1.tgz";
      sha512 = "3I5HiyEv5svyn5wZ+DJ0+Ht+mVVl58Q+YWzpCurZwi2QGDqAaD7vty4LDJ65iFWUMfQdFrQlSP0uZGOfrIngZw==";
    };
    dependencies = [
      sources."@babel/helper-string-parser-7.27.1"
      sources."@babel/helper-validator-identifier-7.28.5"
      sources."@babel/parser-7.29.0"
      sources."@babel/types-7.29.0"
      sources."@prisma/config-6.19.0-dev.10"
      sources."@prisma/prisma-schema-wasm-6.19.0-26.2ba551f319ab1df4bc874a89965d8b3641056773"
      sources."@prisma/schema-files-loader-6.19.0-dev.10"
      sources."@standard-schema/spec-1.1.0"
      sources."@types/js-levenshtein-1.1.3"
      sources."c12-3.1.0"
      sources."chokidar-4.0.3"
      sources."citty-0.1.6"
      sources."confbox-0.2.4"
      sources."consola-3.4.2"
      sources."deepmerge-ts-7.1.5"
      sources."defu-6.1.4"
      sources."destr-2.0.5"
      sources."dotenv-16.6.1"
      sources."effect-3.18.4"
      sources."empathic-2.0.0"
      sources."exsolve-1.0.8"
      sources."fast-check-3.23.2"
      sources."fs-extra-11.3.0"
      sources."giget-2.0.0"
      sources."graceful-fs-4.2.11"
      sources."jiti-2.6.1"
      sources."js-levenshtein-1.1.6"
      sources."jsonfile-6.2.0"
      sources."klona-2.0.6"
      sources."magicast-0.3.5"
      sources."node-fetch-native-1.6.7"
      (sources."nypm-0.6.5" // {
        dependencies = [
          sources."citty-0.2.0"
        ];
      })
      sources."ohash-2.0.11"
      sources."pathe-2.0.3"
      sources."perfect-debounce-1.0.0"
      sources."pkg-types-2.3.0"
      sources."pure-rand-6.1.0"
      sources."rc9-2.1.2"
      sources."readdirp-4.1.2"
      sources."source-map-js-1.2.1"
      sources."tinyexec-1.0.2"
      sources."universalify-2.0.1"
      sources."vscode-jsonrpc-8.1.0"
      sources."vscode-languageserver-8.1.0"
      sources."vscode-languageserver-protocol-3.17.3"
      sources."vscode-languageserver-textdocument-1.0.11"
      sources."vscode-languageserver-types-3.17.3"
      sources."vscode-uri-3.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prisma Language Server";
      homepage = "https://github.com/prisma/language-tools#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
